import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Environex | Excellence at The Highest Level</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    <Navbar />

    {/* start of intro */}
    <section className='pb-5 position-relative bg-accent z-3'>
    <div className="container">
    <div className="row justify-content-center">
    <div className='col-md-3 col-6 text-center col-intro-icon' style={{marginTop:"-50px"}}>
    <div className='position-relative d-inline-block p-2 tab-icon tab-icon-active' style={{borderRadius:"50%",border:"1px solid white"}} id='tab-icon-01'>
    <div className='position-relative bg-accent d-inline-block p-2' style={{borderRadius:"50%"}}>
    <div className={`${styles.imgIcon}`}>
    <Image
    src="/images/Icon-Industrial-Catalyst-Services.png"
    alt="Environex logo"
    // width={115}
    // height={140}
    layout="fill"
    className={`${styles.imgIconInner}`}
    />
    </div>
    </div>

    </div>

    </div>
    </div>
    </div>

    </section>
    {/* end of intro */}
      
      <Footer />

      
    </div>
  )
}
